variables:
  GIT_STRATEGY: none
  CC: mpicc
  CXX: mpicxx
  FC: mpif90
  F77: mpif77
  NEKRS_INSTALL_DIR: $CI_PROJECT_DIR/.local/nekrs
  NEKRS_HOME: $CI_PROJECT_DIR/.local/nekrs
  NEKRS_EXAMPLES: $CI_PROJECT_DIR/.local/nekrs/examples
  OCCA_CACHE_DIR: $CI_PROJECT_DIR/.local/nekrs/occa_cache
  OCCA_CUDA_ENABLED: 0
  OCCA_HIP_ENABLED: 0
  OCCA_OPENCL_ENABLED: 0

stages:
  - prepare
  - warmup
  - test

install:
  stage: prepare
  variables:
    GIT_STRATEGY: clone
  script:
    - rm -rf $NEKRS_HOME 
    - rm -rf build 
    - ./makenrs 

warmup-ethier:
  stage: warmup
  script: 
    - cd $NEKRS_EXAMPLES/ethier 
    - rm -rf .cache 
    - $NEKRS_HOME/bin/nrspre ethier 1

warmup-lowMach:
  stage: warmup
  script: 
    - cd $NEKRS_EXAMPLES/lowMach 
    - rm -rf .cache 
    - $NEKRS_HOME/bin/nrspre lowMach 2

warmup-conj-ht:
  stage: warmup
  script: 
    - cd $NEKRS_EXAMPLES/conj_ht 
    - rm -rf .cache 
    - $NEKRS_HOME/bin/nrspre conj_ht 2

ethier-default:
  stage: test
  script:
    - cd $NEKRS_EXAMPLES/ethier 
    - $NEKRS_HOME/bin/nrsmpi ethier 1

ethier-subcycle:
  stage: test
  script: 
    - cd $NEKRS_EXAMPLES/ethier 
    - $NEKRS_HOME/bin/nrsmpi ethier 2

lowMach-default:
  stage: test
  script: 
    - cd $NEKRS_EXAMPLES/lowMach 
    - $NEKRS_HOME/bin/nrsmpi lowMach 2
  
conj-ht:
  stage: test
  script: 
    - cd $NEKRS_EXAMPLES/conj_ht 
    - $NEKRS_HOME/bin/nrsmpi conj_ht 2

